jobs:
  build:
    defaults:
      run:
        working-directory: boot-data-redis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B package --file pom.xml
name: spring-reactive-boot-data-redis
on:
  repository_dispatch:
    types: trigger-ga___boot-data-redis.yml
