jobs:
  greeting:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/first-interaction@v1
      with:
        issue-message: Thanks for reporting issues
        pr-message: Thanks for sending your prs
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Greetings
on:
  repository_dispatch:
    types: trigger-ga___greetings.yml
