jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build with Maven
      run: 'cd rxjava3

        mvn -B package --file pom.xml

        '
name: spring-reactive-rxjava3
on:
  repository_dispatch:
    types: trigger-ga___rxjava3.yml
