jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Start up databases via Docker Compose
      run: "docker-compose up -d mongodb\nsleep 5\ndocker ps -a          \n"
    - continue-on-error: true
      name: Build with Maven
      run: 'cd session-data-mongo

        mvn -B package --file pom.xml

        '
name: spring-reactive-session-data-mongo
on:
  repository_dispatch:
    types: trigger-ga___session-data-mongo.yml
