jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: 5
        days-before-stale: 30
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: no-issue-activity
        stale-issue-message: Please add extra info to clarify this issue, if none
          provided, it will be marked as stale
        stale-pr-label: no-pr-activity
        stale-pr-message: Please update the pr according to feedbacks, else it will
          be marked as stale
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
